// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh2XkBwUSzBNEaeWmnRf59ZRa_93xh5F4',
    appId: '1:357648170984:android:27875c5ac747a4ae3dae5d',
    messagingSenderId: '357648170984',
    projectId: 'teleo-church-application',
    storageBucket: 'teleo-church-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzETQZMYOvZwnwg0LowA7PjQHpEfKlcI',
    appId: '1:357648170984:ios:0c1e25edf24f47c73dae5d',
    messagingSenderId: '357648170984',
    projectId: 'teleo-church-application',
    storageBucket: 'teleo-church-application.firebasestorage.app',
    iosBundleId: 'com.example.teleoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBGtHeMWcpas1R-ueMBgP1iYUDbwA72K8c",
    authDomain: "teleo-church-application.firebaseapp.com",
    projectId: "teleo-church-application",
    storageBucket: "teleo-church-application.firebasestorage.app",
    messagingSenderId: "357648170984",
    appId: "1:357648170984:web:06bc7156c7b5c9583dae5d",
    measurementId: "G-F15BTPZLP9",
  );
}
