// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGtHeMWcpas1R-ueMBgP1iYUDbwA72K8c',
    appId: '1:357648170984:web:06bc7156c7b5c9583dae5d',
    messagingSenderId: '357648170984',
    projectId: 'teleo-church-application',
    authDomain: 'teleo-church-application.firebaseapp.com',
    storageBucket: 'teleo-church-application.firebasestorage.app',
    measurementId: 'G-F15BTPZLP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh2XkBwUSzBNEaeWmnRf59ZRa_93xh5F4',
    appId: '1:357648170984:android:f32106a00fbbb2603dae5d',
    messagingSenderId: '357648170984',
    projectId: 'teleo-church-application',
    storageBucket: 'teleo-church-application.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGtHeMWcpas1R-ueMBgP1iYUDbwA72K8c',
    appId: '1:357648170984:web:69d99e0ec3bc78de3dae5d',
    messagingSenderId: '357648170984',
    projectId: 'teleo-church-application',
    authDomain: 'teleo-church-application.firebaseapp.com',
    storageBucket: 'teleo-church-application.firebasestorage.app',
    measurementId: 'G-GL1V7LEVL8',
  );
}
