// lib/features/SIGNUP/backend/models/USER_SIGNUPMODELS.dart
import 'package:flutter/material.dart';
import 'package:teleo_app/features/SIGNUP/geolocation/backend/GEO_LOCATIONMODEL.dart'; // Import GeoLocationModel

class UserSignupData {
  // Fields for signup process
  String? firstName;
  String? lastName;
  DateTime? birthday;
  String? gender;
  String? username;
  GeoLocationModel? location;
  String? email;
  String? phoneNumber;
  String? password;
  String? sentCode; // To store the code sent for verification
  bool termsAccepted;
  String? profilePictureUrl;

  // Fields for the final user model (previously in UserModel)
  String? id; // Will be generated by backend
  String? userRole; // e.g., 'user', 'admin'

  UserSignupData({
    this.firstName,
    this.lastName,
    this.birthday,
    this.gender,
    this.username,
    this.location,
    this.email,
    this.phoneNumber,
    this.password,
    this.sentCode,
    this.termsAccepted = false,
    this.profilePictureUrl,
    this.id,
    this.userRole,
  });

  UserSignupData copyWith({
    String? firstName,
    String? lastName,
    DateTime? birthday,
    String? gender,
    String? username,
    GeoLocationModel? location,
    String? email,
    String? phoneNumber,
    String? password,
    String? sentCode,
    bool? termsAccepted,
    String? profilePictureUrl,
    String? id,
    String? userRole,
  }) {
    return UserSignupData(
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      birthday: birthday ?? this.birthday,
      gender: gender ?? this.gender,
      username: username ?? this.username,
      location: location ?? this.location,
      email: email ?? this.email,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      password: password ?? this.password,
      sentCode: sentCode ?? this.sentCode,
      termsAccepted: termsAccepted ?? this.termsAccepted,
      profilePictureUrl: profilePictureUrl ?? this.profilePictureUrl,
      id: id ?? this.id,
      userRole: userRole ?? this.userRole,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id, // Include ID for updates or if backend expects it
      'firstName': firstName,
      'lastName': lastName,
      'birthday': birthday?.toIso8601String(),
      'gender': gender,
      'username': username,
      'address': location?.address, // Flatten location for backend
      'latitude': location?.latitude,
      'longitude': location?.longitude,
      'email': email,
      'phoneNumber': phoneNumber,
      'password': password,
      'profilePictureUrl': profilePictureUrl,
      'termsAccepted': termsAccepted,
      'userRole': userRole,
      // sentCode is internal and not typically sent to backend for registration
    };
  }

  factory UserSignupData.fromJson(Map<String, dynamic> json) {
    return UserSignupData(
      id: json['id'],
      firstName: json['firstName'],
      lastName: json['lastName'],
      birthday: json['birthday'] != null ? DateTime.parse(json['birthday']) : null,
      gender: json['gender'],
      username: json['username'],
      location: (json['address'] != null && json['latitude'] != null && json['longitude'] != null)
          ? GeoLocationModel(
              address: json['address'],
              latitude: json['latitude'],
              longitude: json['longitude'],
            )
          : null,
      email: json['email'],
      phoneNumber: json['phoneNumber'],
      password: json['password'], // Be cautious with password in fromJson for security
      profilePictureUrl: json['profilePictureUrl'],
      termsAccepted: json['termsAccepted'] ?? false,
      userRole: json['userRole'],
    );
  }

  void reset() {
    firstName = null;
    lastName = null;
    birthday = null;
    gender = null;
    username = null;
    location = null;
    email = null;
    phoneNumber = null;
    password = null;
    sentCode = null;
    termsAccepted = false;
    profilePictureUrl = null;
    id = null;
    userRole = null;
  }
}
