import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'USER_SIGNUP_12.dart'; // Corrected import for ProfilePictureScreen
import '../../backend/models/USER_SIGNUP_VAR.dart'; // Import for UserProfile
import '../widgets/index.dart'; // Corrected import for TeleoBackButton and CustomElevatedButton
import '../../backend/viewmodels/USER_SIGNUP_FUNC.dart'; // Import for VerificationService

class VerificationCodeScreen extends StatefulWidget {
  final UserProfile userProfile; // Use UserProfile model
  final String email;
  final String phone;
  final String password;
  final String? sentCode;

  const VerificationCodeScreen({
    super.key,
    required this.userProfile, // Use UserProfile model
    required this.email,
    required this.phone,
    required this.password,
    this.sentCode,
  });

  @override
  State<VerificationCodeScreen> createState() => _VerificationCodeScreenState();
}

class _VerificationCodeScreenState extends State<VerificationCodeScreen> {
  final List<TextEditingController> _controllers = List.generate(
      6,
      (_) => TextEditingController()
  );
  final List<FocusNode> _focusNodes = List.generate(
      6,
      (_) => FocusNode()
  );
  // Cooldown timer variables
  bool _isResendEnabled = true;
  int _cooldownSeconds = 0;
  Timer? _cooldownTimer;

  @override
  void initState() {
    super.initState();
    // Simulate sending the initial verification code
    _startCooldownTimer();
  }

  @override
  void dispose() {
    for (var controller in _controllers) {
      controller.dispose();
    }
    for (var node in _focusNodes) {
      node.dispose();
    }
    _cooldownTimer?.cancel();
    super.dispose();
  }

  void _startCooldownTimer() {
    setState(() {
      _isResendEnabled = false;
      _cooldownSeconds = 300; // 5 minutes in seconds
    });
    _cooldownTimer = Timer.periodic(const Duration(seconds: 1), (timer) {
      setState(() {
        if (_cooldownSeconds > 0) {
          _cooldownSeconds--;
        } else {
          _isResendEnabled = true;
          timer.cancel();
        }
      });
    });
  }

  String get _formatCooldownTime {
    final minutes = (_cooldownSeconds / 60).floor();
    final seconds = _cooldownSeconds % 60;
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  bool get _isCodeComplete {
    for (var controller in _controllers) {
      if (controller.text.isEmpty) {
        return false;
      }
    }
    return true;
  }

  String get _fullCode {
    return _controllers.map((controller) => controller.text).join();
  }

  void _resendCode() async { // Made async to await service call
    if (!_isResendEnabled) return;

    final resendStatus = await VerificationService.resendCode(
      widget.email,
      '${widget.userProfile.firstName} ${widget.userProfile.lastName}',
    );

    if (!mounted) return; // Check if widget is still mounted after async operation

    if (resendStatus == "sent") {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Verification code resent to your email'),
        ),
      );
      _startCooldownTimer(); // Restart the UI cooldown timer
    } else if (resendStatus == "cooldown") {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please wait before resending the code.'),
        ),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Failed to resend code. Please try again.'),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              // Back button row
              const Align(
                alignment: Alignment.centerLeft,
                child: Padding(
                  padding: EdgeInsets.only(top: 16.0),
                  child: TeleoBackButton(),
                ),
              ),
              const SizedBox(height: 40),
              const Text(
                "We've sent a code to your email!",
                style: TextStyle(
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16),
              const Text(
                "Enter the six digit code generated by your authentication app.",
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.black54,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 60),
              // Verification code input
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: List.generate(
                  6,
                  (index) => SizedBox(
                    width: 45,
                    height: 60,
                    child: TextField(
                      controller: _controllers[index],
                      focusNode: _focusNodes[index],
                      textAlign: TextAlign.center,
                      keyboardType: TextInputType.number,
                      maxLength: 1,
                      decoration: InputDecoration(
                        counterText: '',
                        contentPadding: EdgeInsets.zero,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(color: Colors.grey.shade300),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(color: Colors.grey.shade300),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                          borderSide: const BorderSide(color: Color(0xFF002642)),
                        ),
                      ),
                      inputFormatters: [
                        FilteringTextInputFormatter.digitsOnly,
                      ],
                      onChanged: (value) {
                        if (value.isNotEmpty && index < 5) {
                          _focusNodes[index + 1].requestFocus();
                        }
                        setState(() {});
                      },
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 40),
              // Resend code with cooldown
              GestureDetector(
                onTap: _isResendEnabled ? _resendCode : null,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      "Haven't got the code yet? ",
                      style: TextStyle(
                        color: Colors.grey.shade600,
                        fontSize: 14,
                      ),
                    ),
                    Text(
                      _isResendEnabled
                          ? "Resend code"
                          : "Resend code ($_formatCooldownTime)",
                      style: TextStyle(
                        color: _isResendEnabled ? Colors.blue : Colors.grey.shade400,
                        fontSize: 14,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              const Spacer(),
              // Next button using CustomElevatedButton
              Padding(
                padding: const EdgeInsets.only(bottom: 40.0),
                child: CustomElevatedButton( // Using CustomElevatedButton
                  text: 'Next',
                  onPressed: _isCodeComplete
                      ? () {
                          final updatedUserProfile = UserProfile(
                            firstName: widget.userProfile.firstName,
                            lastName: widget.userProfile.lastName,
                            birthday: widget.userProfile.birthday,
                            gender: widget.userProfile.gender,
                            username: widget.userProfile.username,
                            address: widget.userProfile.address,
                            location: widget.userProfile.location,
                            // Add email, phone, password, verificationCode to UserProfile if you want to persist them
                            // email: widget.email,
                            // phone: widget.phone,
                            // password: widget.password,
                            // verificationCode: _fullCode,
                          );
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => ProfilePictureScreen(
                                userProfile: updatedUserProfile,
                                email: widget.email,
                                phone: widget.phone,
                                password: widget.password,
                                verificationCode: _fullCode,
                              ),
                            ),
                          );
                        }
                      : null,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
