// This file contains the shared data model for volunteers

// Dummy data for volunteers
final List<Map<String, dynamic>> dummyVolunteers = [
  // Original 5 records - kept intact without report messages
  {
    'id': '1',
    'name': 'Alyssa Elona',
    'church': 'Grace Church',
    'status': 'Accepted',
    'date': 'March 15, 2025',
    'isReported': false,
    'personalInfo': {
      'email': 'alyssa.elona@example.com',
      'phone': '+1 (555) 123-4567',
      'address': '123 Main St, Anytown, USA',
      'age': 28,
      'gender': 'Female',
      'occupation': 'Teacher',
    },
    'applicationForm': {
      'submissionDate': 'February 28, 2025',
      'positionApplied': 'Worship Team',
      'previousExperience': '5 years as worship leader at previous church',
      'availability': 'Weekends and Wednesday evenings',
      'specialSkills': 'Piano, guitar, vocals',
      'references': 'Pastor John (555-789-1234), Deacon Mary (555-987-6543)',
    },
  },
  {
    'id': '2',
    'name': 'Brent Damian',
    'church': 'Happy Family Church',
    'status': 'Accepted',
    'date': 'March 18, 2025',
    'isReported': false,
    'wantsToExit': true,
    'exitForm': {
      'submissionDate': 'April 5, 2025',
      'reason': 'Personal commitment',
      'description': 'I have a family emergency that requires my full attention for the next few months.',
    },
    'personalInfo': {
      'email': 'brent.damian@example.com',
      'phone': '+1 (555) 234-5678',
      'address': '456 Oak Ave, Somewhere, USA',
      'age': 32,
      'gender': 'Male',
      'occupation': 'Software Developer',
    },
    'applicationForm': {
      'submissionDate': 'March 1, 2025',
      'positionApplied': 'Tech Team',
      'previousExperience': '3 years managing church tech at previous congregation',
      'availability': 'Sundays and special events',
      'specialSkills': 'Audio/visual equipment, livestreaming, website management',
      'references': 'Tech Director Sam (555-456-7890), Pastor Lisa (555-321-6547)',
    },
  },
  {
    'id': '3',
    'name': 'Crissie Folloso',
    'church': 'Amen Praise Community',
    'status': 'Pending',
    'date': 'March 20, 2025',
    'isReported': false,
    'personalInfo': {
      'email': 'crissie.folloso@example.com',
      'phone': '+1 (555) 345-6789',
      'address': '789 Pine Ln, Elsewhere, USA',
      'age': 25,
      'gender': 'Female',
      'occupation': 'Nurse',
    },
    'applicationForm': {
      'submissionDate': 'March 10, 2025',
      'positionApplied': 'Children\'s Ministry',
      'previousExperience': '2 years as Sunday school teacher',
      'availability': 'Sunday mornings and special events',
      'specialSkills': 'First aid certified, storytelling, arts and crafts',
      'references': 'Nurse Manager Jane (555-678-9012), Pastor Robert (555-890-1234)',
    },
  },
  {
    'id': '4',
    'name': 'Danpaul Gonzaga',
    'church': 'Heaven Highway Camp',
    'status': 'Rejected',
    'date': 'March 5, 2025',
    'rejectionReason': 'Background Check Issues',
    'rejectionDescription': 'Failed to pass the required background check for working with vulnerable populations.',
    'isReported': false,
    'personalInfo': {
      'email': 'danpaul.gonzaga@example.com',
      'phone': '+1 (555) 456-7890',
      'address': '101 Maple Dr, Nowhere, USA',
      'age': 35,
      'gender': 'Male',
      'occupation': 'Construction Worker',
    },
    'applicationForm': {
      'submissionDate': 'February 20, 2025',
      'positionApplied': 'Facilities Team',
      'previousExperience': 'No previous church volunteer experience',
      'availability': 'Saturdays and weekday evenings',
      'specialSkills': 'Carpentry, electrical work, general maintenance',
      'references': 'Foreman Bill (555-234-5678), Neighbor Tom (555-345-6789)',
    },
  },
  {
    'id': '5',
    'name': 'Elcmar De Guzman',
    'church': 'Dark System',
    'status': 'Pending',
    'date': 'March 20, 2025',
    'isReported': false,
    'personalInfo': {
      'email': 'elcmar.deguzman@example.com',
      'phone': '+1 (555) 567-8901',
      'address': '202 Cedar St, Anyplace, USA',
      'age': 29,
      'gender': 'Male',
      'occupation': 'Accountant',
    },
    'applicationForm': {
      'submissionDate': 'March 15, 2025',
      'positionApplied': 'Finance Team',
      'previousExperience': '5 years managing finances for non-profit organizations',
      'availability': 'Weekday evenings and as needed',
      'specialSkills': 'Bookkeeping, budgeting, financial reporting',
      'references': 'CFO Sarah (555-456-7890), Pastor Michael (555-678-9012)',
    },
  },
  
  // New dummy records with report functionality
  {
    'id': '6',
    'name': 'John Doe',
    'church': 'Faith Community Church',
    'status': 'Pending',
    'date': 'March 22, 2025',
    'isReported': true,
    'reportReason': 'Rude',
    'reportDescription': 'Inaway ako na bakit daw ako ang sinama at hindi si Fyang sa volunteers eh siya ang kween at hampas lupa lang daw ako.',
    'personalInfo': {
      'email': 'john.doe@example.com',
      'phone': '+1 (555) 111-2222',
      'address': '505 Elm Street, Springfield, USA',
      'age': 34,
      'gender': 'Male',
      'occupation': 'Marketing Manager',
    },
    'applicationForm': {
      'submissionDate': 'March 12, 2025',
      'positionApplied': 'Communications Team',
      'previousExperience': '7 years in church communications and social media',
      'availability': 'Weekends and Thursday evenings',
      'specialSkills': 'Graphic design, social media management, content creation',
      'references': 'Pastor Williams (555-222-3333), Media Director Sarah (555-444-5555)',
    },
  },
  {
    'id': '7',
    'name': 'Analise Bell',
    'church': 'Grace Fellowship',
    'status': 'Accepted',
    'date': 'March 19, 2025',
    'isReported': true,
    'reportReason': 'Rude',
    'reportDescription': 'Inaway ako na bakit daw ako ang sinama at hindi si Fyang sa volunteers eh siya ang kween at hampas lupa lang daw ako.',
    'wantsToExit': true,
    'exitForm': {
      'submissionDate': 'April 2, 2025',
      'reason': 'Schedule conflict',
      'description': 'I have taken on additional responsibilities at work that conflict with the volunteer schedule.',
    },
    'personalInfo': {
      'email': 'analise.bell@example.com',
      'phone': '+1 (555) 666-7777',
      'address': '789 Willow Ave, Lakeside, USA',
      'age': 27,
      'gender': 'Female',
      'occupation': 'Event Planner',
    },
    'applicationForm': {
      'submissionDate': 'March 5, 2025',
      'positionApplied': 'Hospitality Team',
      'previousExperience': '4 years coordinating church events and gatherings',
      'availability': 'Weekends and flexible weekdays',
      'specialSkills': 'Event planning, hospitality coordination, volunteer management',
      'references': 'Pastor Roberts (555-888-9999), Events Coordinator Michael (555-000-1111)',
    },
  },
];
